version: '3'
services:

  azship-db:
    image: postgres:latest
    container_name: azship-db 
    restart: always
    networks:
        - ship-network
    environment:
      - POSTGRES_DB=ship-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234567
    ports: 
      - 5433:5432

  azship-mongodb:
    image: mongo:latest
    container_name: azship-mongodb
    restart: always
    networks:
      - ship-network
    environment:  
      - MONGODB_DATABASE=ship-db
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=123456
    ports: 
      - 27017:27017

  azship-restapi:
      build: './desafio-az'
      container_name: azship-rest
      depends_on:
        - azship-db
      networks:
        - ship-network
      environment:
        - PORT=8080
        - DB_HOST=azship-db
        - DB_NAME=ship-db
        - DB_USER=admin
        - DB_PASSWORD=1234567
        - DB_PORT=5432
      ports: 
        - 8081:8080

  ship-graphqlapi:
      build: './azShipMongo'
      container_name: azship-graphql
      depends_on:
        - azship-mongodb
      networks:
        - ship-network
      environment:
        - PORT=8080
        - DB_HOST=azship-mongodb
        - DB_NAME=azship-db
        - DB_USER=admin
        - DB_PASSWORD=123456
        - DB_PORT=27017
      ports: 
        - 8080:8080

networks:
  ship-network:
    driver: bridge
